services:
  alfebot:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: alfebot

    restart: unless-stopped

    env_file:
      - ../.env

    volumes:
      - alfebot-data:/app/data

    network_mode: host

    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  alfebot-data: